### PR TITLE
support new goModules attr

### PR DESCRIPTION
**Pull request by Artturin**
go-modules has been renamed to goModules

for nixpkgs https://github.com/NixOS/nixpkgs/pull/242905

### CODE REVIEW

**Review by SuperSandro2000 — COMMENTED** [review]
I think we should both for some time

**Comment by Mic92** [comment]
@mergify queue

**Comment by Artturin** [comment]
Should i pull this as a patch to nix-update or do you want to make a release

**Comment by Mic92** [comment]
https://github.com/Mic92/nix-update/releases/tag/0.19.0

**Pull request merged**
