### PR TITLE
Skip updating hashes without version change

### PR DESCRIPTION
**Pull request by NeQuissimus**
This is going to require an opinion, I think :)

I don't know if you have a use case for updates that only change the hash (seems weird to me but maybe there is a reason).
Anyways, I have a use case against that:

Maintainers on different nix versions currently swap between the old SHA256 and the new notation.
This confuses `nix-update` and triggers commits that purely change the hash format (but get committed as `PACKAGE: 1.2.3 -> 1.2.3` with `--commit`).

This change will not trigger hash changes if the version has not been updated.

### CODE REVIEW

**Comment by Mic92** [comment]
Actually I use this sometimes and than fix the version number manually :). Sometimes I have updated the version number upfront. But I see your point.

**Comment by NeQuissimus** [comment]
I think the way I set the default boolean, the functionality should still be available if `opts.version` is `skip`

**Comment by Mic92** [comment]
@NeQuissimus how do you like this solution? https://github.com/Mic92/nix-update/pull/28

**Comment by NeQuissimus** [comment]
@Mic92 It won't help with people not running `nix-updates` but updating manually. But I think I can live with that. One additional thought: Is there a way we could teach the git commit logic about this?
Instead of `pkg: 1.2.3 -> 1.2.3`, could you make it say `pkg: Normalize hash` or something like that?

**Comment by Mic92** [comment]
I will scrape the version diff from: `git diff --word-diff=porcelain`

**Comment by Mic92** [comment]
> @Mic92 It won't help with people not running `nix-updates` but updating manually. But I think I can live with that. One additional thought: Is there a way we could teach the git commit logic about this?
> Instead of `pkg: 1.2.3 -> 1.2.3`, could you make it say `pkg: Normalize hash` or something like that?

I think after https://github.com/Mic92/nix-update/pull/30 we add the logic you proposed.

**Pull request merged**
