### PR TITLE
fix hash replace

### PR DESCRIPTION
**Pull request by trim21**
close https://github.com/Mic92/nix-update/issues/292

### CODE REVIEW

**Comment by Mic92** [comment]
Mhm. I cannot reproduce the error you describe in the issue:

```
$ git -C /home/joerg/git/nixpkgs diff -- /home/joerg/git/nixpkgs/pkgs/tools/admin/lego/default.nix
$ git -C /home/joerg/git/nixpkgs commit --verbose --message lego: 4.17.4 -> 4.19.2

Diff: https://github.com/go-acme/lego/compare/v4.17.4...v4.19.2 /home/joerg/git/nixpkgs/pkgs/tools/admin/lego/default.nix
[main b8210103e173] lego: 4.17.4 -> 4.19.2
 1 file changed, 3 insertions(+), 3 deletions(-)
  5.10s user 2.13s system 8% cpu 1:25.45 total
```

```
diff --git a/pkgs/tools/admin/lego/default.nix b/pkgs/tools/admin/lego/default.nix
index 5ff28355bc7c..3af94d79ad42 100644
--- a/pkgs/tools/admin/lego/default.nix
+++ b/pkgs/tools/admin/lego/default.nix
@@ -2,16 +2,16 @@
 
 buildGoModule rec {
   pname = "lego";
-  version = "4.17.4";
+  version = "4.19.2";
 
   src = fetchFromGitHub {
     owner = "go-acme";
     repo = pname;
     rev = "v${version}";
-    sha256 = "sha256-DF9Bx6CzZLdnyqe8PNWU2I9ym2SBDAjdwG9/zxvSjgs=";
+    sha256 = "sha256-O4lzOZUiicmahxcbzPsEU2+tPDTCUun2JLeWZjpTZIQ=";
   };
 
-  vendorHash = "sha256-tX/QpAZLuQEYhm1I1twlg3TefaLqfiEz9cXID+r6EHA=";
+  vendorHash = "sha256-BcE/8pxQdJp9vttLo4wDSUswJnaBhIn/mlt3ZcOf2wA=";
 
   doCheck = false;
 
```

**Comment by Mic92** [comment]
Can you give me instruction how to reproduce the issue?

**Comment by trim21** [comment]
I'm not using NixOS, but nixpkgs with debian 12, and also I didn't install nix-update with nixpkgs ( python from nixpkgs is broken on my os). I install nix-update with `pipx install git+https://github.com/Mic92/nix-update` with python 3.11

Then clone https://github.com/NixOS/nixpkgs, run `nix-update` and vendor hash not changed.

**Comment by Mic92** [comment]
It also seems to be not related to python3.11 at all. Interestingly this repo still pinned python3.11 and it still worked for me.

**Comment by Mic92** [comment]
It's also weird that it works for updating the src hash but not for the `vendorHash`, because that's the very same function.

**Comment by trim21** [comment]
test it again, I think it's not actually a bug....

vendorHash updating works fine, but long time after source hash are updated.

**Comment by Mic92** [comment]
Maybe you ctrl-c-ed nix-update before it was finished.

**Pull request closed without merging**
