### PR TITLE
Add support for updating pnpmDeps

### PR DESCRIPTION
**Pull request by Scrumplex**
Now that https://github.com/NixOS/nixpkgs/pull/290715, it would be nice to have some update tooling :D

You can test this with the package `pot`, as it is one patch version behind on master.

https://github.com/pot-app/pot-desktop/releases

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Can we add a test for it?

**Comment by Scrumplex** [comment]
I actually have one in my local tree, but as the PR in question hasn't hit `nixpkgs-unstable` yet, I wasn't able to run it.

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
I plan to publish a new version soon, in case you want to add this one as well.

**Comment by Scrumplex** [comment]
The pnpm tooling is still not in `nixpkgs-unstable` yet, so I can't add a test for it yet :O

https://nixpk.gs/pr-tracker.html?pr=290715

**Comment by Mic92** [comment]
Looks like it's now in nixpkgs-unstable.

**Comment by Scrumplex** [comment]
This should be ready to merge!

I also made the tests use the Nixpkgs pinned in the flake when using the default devShell.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
